/*
 * This source file was generated by the Gradle 'init' task
 */
package me.rainma22.mcptester

import java.awt.Color
import java.awt.Dimension
import java.awt.Font
import java.awt.Rectangle
import javax.swing.JFrame
import javax.swing.JLabel
import javax.swing.JTextPane
import javax.swing.border.Border
import javax.swing.border.LineBorder


class App : JFrame() {
    val greeting: String
        get() {
            return "Hello World!"
        }

    init {
        setTitle("MCPTester")
        bounds = Rectangle(1920, 1080)
        layout = null
        val msg = JLabel()
        msg.bounds = Rectangle(100,100, 800, 500)
        msg.font = Font(msg.font.name, msg.font.style, 64)
        msg.text = greeting
        msg.border = LineBorder(Color(0x000000), 1)
        add(msg)
        defaultCloseOperation = EXIT_ON_CLOSE
        isVisible = true
    }
}

fun main() {
    println(App().greeting)
}


